export function buildStats(data) {
  const byYear = {};
  const byStatus = {};
  const byWeightsStatus = {};
  for (const release of data.releases) {
    const year = release.date.slice(0, 4);
    byYear[year] = (byYear[year] || 0) + 1;
    byStatus[release.status] = (byStatus[release.status] || 0) + 1;
    byWeightsStatus[release.weightsStatus] = (byWeightsStatus[release.weightsStatus] || 0) + 1;
  }
  const dates = data.releases.map((release) => release.date).sort();
  const linked = data.releases.filter((release) => release.artificialAnalysisUrl);
  const weights = data.releases.filter((release) => release.huggingFaceUrl);
  return {
    snapshot: data.updated,
    familyCount: data.families.length,
    releaseCount: data.releases.length,
    sourceCount: data.sources.length,
    artificialAnalysisReleaseCount: linked.length,
    artificialAnalysisProfileCount: new Set(linked.map((r) => r.artificialAnalysisUrl)).size,
    huggingFaceReleaseCount: weights.length,
    huggingFaceLinkCount: new Set(weights.map((r) => r.huggingFaceUrl)).size,
    releasesByWeightsStatus: Object.fromEntries(Object.entries(byWeightsStatus).sort()),
    firstEventDate: dates[0] ?? null,
    lastEventDate: dates.at(-1) ?? null,
    releasesByYear: Object.fromEntries(Object.entries(byYear).sort()),
    releasesByStatus: Object.fromEntries(Object.entries(byStatus).sort()),
    families: data.families.map((family) => {
      const releases = data.releases.filter((release) => release.family === family.id);
      if (!releases.length) throw new Error(`Cannot summarize empty family: ${family.id}`);
      const highestScore = Math.max(...releases.map((release) => release.score));
      const first = releases
        .filter((release) => release.score === highestScore)
        .sort((a, b) => a.date.localeCompare(b.date) || a.name.localeCompare(b.name))[0];
      const familyDates = releases.map((release) => release.date).sort();
      return {
        id: family.id,
        name: family.name,
        releaseCount: releases.length,
        versionCount: new Set(releases.map((release) => release.score)).size,
        highestVersion: first.version,
        highestScore,
        firstReleaseAtHighestVersion: { id: first.id, name: first.name, date: first.date },
        firstEventDate: familyDates[0],
        lastEventDate: familyDates.at(-1),
        artificialAnalysisReleaseCount: releases.filter((r) => r.artificialAnalysisUrl).length,
        huggingFaceReleaseCount: releases.filter((r) => r.huggingFaceUrl).length,
      };
    }),
  };
}

export function statsSummary(stats) {
  return `Snapshot **${stats.snapshot}** · **${stats.familyCount} families** · **${stats.releaseCount} release events** · **${stats.sourceCount} sources** · **${stats.artificialAnalysisReleaseCount} releases linked to Artificial Analysis** · **${stats.huggingFaceReleaseCount} releases linked to Hugging Face weights**`;
}

export const readmeTemplates = [
  ['docs/templates/README.md', 'README.md'],
  ['docs/templates/data-README.md', 'data/README.md'],
];

export function renderReadme(template, stats, sourcePath) {
  if (template.split('{{STATS_SUMMARY}}').length !== 2)
    throw new Error(`Expected exactly one stats placeholder in ${sourcePath}`);
  return (
    `<!-- Generated by scripts/generate.mjs. Edit ${sourcePath} instead. -->\n\n` +
    template.replace('{{STATS_SUMMARY}}', () => statsSummary(stats))
  );
}
